# Generated by Django 2.0.1 on 2018-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('name', models.CharField(help_text='Enter the Student Name', max_length=50, verbose_name='Student Name')),
                ('stu_id', models.CharField(help_text='Enter the Student ID', max_length=15, primary_key=True, serialize=False, verbose_name='Student ID')),
                ('status', models.CharField(help_text='Enter the Status', max_length=1, verbose_name='Student Status')),
            ],
        ),
    ]
