# Generated by Django 2.0.1 on 2018-01-23 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stu_att', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stu_att.Student_Details')),
            ],
        ),
    ]
