# Generated by Django 2.0.1 on 2018-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_att', '0002_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='status',
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='status',
            field=models.CharField(default='0', help_text='Enter the Status', max_length=1, verbose_name='Student Status'),
        ),
    ]
