# Generated by Django 2.0.1 on 2018-01-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_att', '0003_auto_20180124_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_attendance',
            name='date',
            field=models.CharField(default='00/00/00', help_text='Enter the Date', max_length=15, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='duration',
            field=models.CharField(blank=True, help_text='Enter the Duration', max_length=15, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='in_time',
            field=models.CharField(default='00:00:00', help_text='Enter the IN Time', max_length=15, verbose_name='IN Time'),
        ),
        migrations.AddField(
            model_name='student_attendance',
            name='out_time',
            field=models.CharField(blank=True, help_text='Enter the OUT Time', max_length=15, null=True, verbose_name='OUT Time'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='address',
            field=models.CharField(help_text='Enter the Student Address', max_length=50, null=True, verbose_name='Student Address'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='g_name',
            field=models.CharField(help_text='Enter the Student Guardian Name', max_length=50, null=True, verbose_name='Guardian Name'),
        ),
        migrations.AddField(
            model_name='student_details',
            name='phone',
            field=models.CharField(help_text='Enter Guardian Number', max_length=15, null=True, verbose_name='Guardian Phone'),
        ),
    ]
